// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/api/[project_id]/campaigns/[campaign]/events.ts";
import * as $4 from "./routes/api/[project_id]/providers/[provider]/register.ts";
import * as $5 from "./routes/api/[project_id]/providers/[provider]/unregister.ts";
import * as $6 from "./routes/api/[project_id]/recipient/events.ts";
import * as $7 from "./routes/api/scripts/[project_id]/integration.ts";
import * as $8 from "./routes/api/scripts/[project_id]/worker.ts";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/projects/[project_id]/campaigns/[campaign_id].tsx";
import * as $11 from "./routes/projects/[project_id]/campaigns/send.tsx";
import * as $12 from "./routes/projects/[project_id]/index.tsx";
import * as $13 from "./routes/projects/new.tsx";
import * as $$0 from "./islands/campaign_form.tsx";
import * as $$1 from "./islands/chart.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/api/[project_id]/campaigns/[campaign]/events.ts": $3,
    "./routes/api/[project_id]/providers/[provider]/register.ts": $4,
    "./routes/api/[project_id]/providers/[provider]/unregister.ts": $5,
    "./routes/api/[project_id]/recipient/events.ts": $6,
    "./routes/api/scripts/[project_id]/integration.ts": $7,
    "./routes/api/scripts/[project_id]/worker.ts": $8,
    "./routes/index.tsx": $9,
    "./routes/projects/[project_id]/campaigns/[campaign_id].tsx": $10,
    "./routes/projects/[project_id]/campaigns/send.tsx": $11,
    "./routes/projects/[project_id]/index.tsx": $12,
    "./routes/projects/new.tsx": $13,
  },
  islands: {
    "./islands/campaign_form.tsx": $$0,
    "./islands/chart.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
